%计算Jacobian矩阵，包含非线性项和线性项
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
JacobiMLI=K1+KT1*DeltaT;%计算原方程组的Jacobian矩阵中的线性相关项
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %计算原方程组的Jacobian矩阵中的非线性相关项
JacobiMNL=zeros(5*N^2);%赋值Jacobian矩阵中非线性项
    %建立ri矩阵
% II=eye(N^2);
% ri1=zeros(N^2,1);
% for i=1:1:N^2
%     ri1(i,1)=1/r(1,ceil(i/N));
% end
% ri2=zeros(N^2,1);
% for i=1:1:N^2
%     ri2(i,1)=1/(r(1,ceil(i/N))^2);
% end
% ri3=zeros(N^2,1);
% for i=1:1:N^2
%     ri3(i,1)=1/(r(1,ceil(i/N))^3);
% end
% ri4=zeros(N^2,1);
% for i=1:1:N^2
%     ri4(i,1)=1/(r(1,ceil(i/N))^4);
% end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（1,3）*(N^2*N^2)矩阵块
JacobiMNL(1:N^2,2*N^2+1:3*N^2)=A11*(SJTP(RR1*dispwc,R1)+SJTP(R1*dispwc,RR1)...
    +1/2*SJTP(ri1,2*SJTP(R1*dispwc,R1)))...
    +A12*(-1/2*SJTP(ri3,2*SJTP(Th1*dispwc,Th1))...
    +SJTP(ri2,SJTP(ThR*dispwc,Th1)+SJTP(Th1*dispwc,ThR))...
    -1/2*SJTP(ri1,2*SJTP(R1*dispwc,R1)))...
    -A22*1/2*SJTP(ri3,2*SJTP(Th1*dispwc,Th1))...
    +A44*(SJTP(ri2,SJTP(ThR*dispwc,Th1)+SJTP(Th1*dispwc,ThR))...
    +SJTP(ri2,SJTP(ThTh1*dispwc,R1)+SJTP(R1*dispwc,ThTh1)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（2,3）*(N^2*N^2)矩阵块
JacobiMNL(N^2+1:2*N^2,2*N^2+1:3*N^2)=A12*SJTP(ri1,SJTP(ThR*dispwc,R1)+SJTP(R1*dispwc,ThR))...
    +A22*SJTP(ri3,SJTP(ThTh1*dispwc,Th1)+SJTP(Th1*dispwc,ThTh1))...
    +A44*(SJTP(ri2,SJTP(Th1*dispwc,R1)+SJTP(R1*dispwc,Th1))...
    +SJTP(ri1,SJTP(RR1*dispwc,Th1)+SJTP(Th1*dispwc,RR1))...
    +SJTP(ri1,SJTP(ThR*dispwc,R1)+SJTP(R1*dispwc,ThR)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（3,1）*(N^2*N^2)矩阵块
JacobiMNL(2*N^2+1:3*N^2,1:N^2)=A11*(SJTP(ri1,SJTP(R1*dispwc,R1))...
    +SJTP(R1*dispwc,RR1)+SJTP(RR1*dispwc,R1))...
    +A12*(SJTP(ri1,SJTP(R1*dispwc,R1))+SJTP(ri1,SJTP(RR1*dispwc,II))...
    +SJTP(ri2,SJTP(Th1*dispwc,ThR))+SJTP(ri2,SJTP(ThTh1*dispwc,R1)))...
    +A22*(SJTP(ri3,SJTP(Th1*dispwc,Th1))+SJTP(ri3,SJTP(ThTh1*dispwc,II)))...
    +A44*(-SJTP(ri3,SJTP(Th1*dispwc,Th1))+SJTP(ri2,SJTP(Th1*dispwc,ThR))...
    +SJTP(ri2,SJTP(R1*dispwc,ThTh1))+2*SJTP(ri2,SJTP(ThR*dispwc,Th1)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（3,2）*(N^2*N^2)矩阵块
JacobiMNL(2*N^2+1:3*N^2,N^2+1:2*N^2)=A12*(SJTP(ri1,SJTP(R1*dispwc,ThR))...
    +SJTP(ri1,SJTP(RR1*dispwc,Th1)))...
    +A22*(SJTP(ri3,SJTP(Th1*dispwc,ThTh1))+SJTP(ri3,SJTP(ThTh1*dispwc,Th1)))...
    +A44*(SJTP(ri1,SJTP(Th1*dispwc,RR1))+SJTP(ri3,SJTP(Th1*dispwc,II))...
    -SJTP(ri2,SJTP(Th1*dispwc,R1))+SJTP(ri1,SJTP(R1*dispwc,ThR))...
    -SJTP(ri2,SJTP(R1*dispwc,Th1))+2*SJTP(ri1,SJTP(ThR*dispwc,R1))...
    -2*SJTP(ri2,SJTP(ThR*dispwc,II)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（3,3）*(N^2*N^2)矩阵块
JacobiMNL(2*N^2+1:3*N^2,2*N^2+1:3*N^2)=A11*(SJTP(ri1,SJTP(R1*dispuc,R1))...
    +SJTP(RR1*dispuc,R1)+SJTP(R1*dispuc,RR1))...
    +A12*(SJTP(ri1,SJTP(R1*dispuc,R1))+SJTP(ri1,SJTP(II*dispuc,RR1))...
    +SJTP(ri2,SJTP(ThR*dispuc,Th1))+SJTP(ri2,SJTP(R1*dispuc,ThTh1)))...
    +A22*(SJTP(ri3,SJTP(Th1*dispuc,Th1))+SJTP(ri3,SJTP(II*dispuc,ThTh1)))...
    +A44*(-SJTP(ri3,SJTP(Th1*dispuc,Th1))+SJTP(ri2,SJTP(ThR*dispuc,Th1))...
    +SJTP(ri2,SJTP(ThTh1*dispuc,R1))+2*SJTP(ri2,SJTP(Th1*dispuc,ThR)))...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    +A12*(SJTP(ri1,SJTP(ThR*dispvc,R1))+SJTP(ri1,SJTP(Th1*dispvc,RR1)))...
    +A22*(SJTP(ri3,SJTP(ThTh1*dispvc,Th1))+SJTP(ri3,SJTP(Th1*dispvc,ThTh1)))...
    +A44*(SJTP(ri1,SJTP(RR1*dispvc,Th1))+SJTP(ri3,SJTP(II*dispvc,Th1))...
    -SJTP(ri2,SJTP(R1*dispvc,Th1))+SJTP(ri1,SJTP(ThR*dispvc,R1))...
    -SJTP(ri2,SJTP(Th1*dispvc,R1))+2*SJTP(ri1,SJTP(R1*dispvc,ThR))...
    -2*SJTP(ri2,SJTP(II*dispvc,ThR)))...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    +B11*(SJTP(ri1,SJTP(R1*dispphirc,R1))+SJTP(RR1*dispphirc,R1)...
    +SJTP(R1*dispphirc,RR1))...
    +B12*(SJTP(ri1,SJTP(R1*dispphirc,R1))+SJTP(ri1,SJTP(II*dispphirc,RR1))...
    +SJTP(ri2,SJTP(ThR*dispphirc,Th1))+SJTP(ri2,SJTP(R1*dispphirc,ThTh1)))...
    +B22*(SJTP(ri3,SJTP(Th1*dispphirc,Th1))+SJTP(ri3,SJTP(II*dispphirc,ThTh1)))...
    +B44*(-SJTP(ri3,SJTP(Th1*dispphirc,Th1))+SJTP(ri2,SJTP(ThR*dispphirc,Th1))...
    +SJTP(ri2,SJTP(ThTh1*dispphirc,R1))+2*SJTP(ri2,SJTP(Th1*dispphirc,ThR)))...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    +B12*(SJTP(ri1,SJTP(ThR*dispphithc,R1))+SJTP(ri1,SJTP(Th1*dispphithc,RR1)))...
    +B22*(SJTP(ri3,SJTP(ThTh1*dispphithc,Th1))+SJTP(ri3,SJTP(Th1*dispphithc,ThTh1)))...
    +B44*(SJTP(ri1,SJTP(RR1*dispphithc,Th1))+SJTP(ri3,SJTP(II*dispphithc,Th1))...
    -SJTP(ri2,SJTP(R1*dispphithc,Th1))+SJTP(ri1,SJTP(ThR*dispphithc,R1))...
    -SJTP(ri2,SJTP(Th1*dispphithc,R1))+2*SJTP(ri1,SJTP(R1*dispphithc,ThR))...
    -2*SJTP(ri2,SJTP(II*dispphithc,ThR)))...%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    +A11*(3/2*SJTP(ri1,SJTP((R1*dispwc).*(R1*dispwc),R1))...
    +3/2*(2*SJTP((R1*dispwc).*(RR1*dispwc),R1)+SJTP((R1*dispwc).*(R1*dispwc),RR1)))...
    +A12*(-1/2*SJTP(ri3,2*SJTP((Th1*dispwc).*(R1*dispwc),Th1)+SJTP((Th1*dispwc).*(Th1*dispwc),R1))...
    +2*SJTP(ri2,SJTP((Th1*dispwc).*(ThR*dispwc),R1)+SJTP((R1*dispwc).*(ThR*dispwc),Th1)...
    +SJTP((R1*dispwc).*(Th1*dispwc),ThR))...
    +1/2*SJTP(ri2,2*SJTP((Th1*dispwc).*(RR1*dispwc),Th1)+SJTP((Th1*dispwc).*(Th1*dispwc),RR1))...
    +1/2*SJTP(ri2,2*SJTP((R1*dispwc).*(ThTh1*dispwc),R1)+SJTP((R1*dispwc).*(R1*dispwc),ThTh1)))...
    +A22*(3/2*SJTP(ri4,2*SJTP((Th1*dispwc).*(ThTh1*dispwc),Th1)+SJTP((Th1*dispwc).*(Th1*dispwc),ThTh1)))...
    +A44*(-SJTP(ri3,2*SJTP((R1*dispwc).*(Th1*dispwc),Th1)+SJTP((Th1*dispwc).*(Th1*dispwc),R1))...
    +SJTP(ri2,2*SJTP((RR1*dispwc).*(Th1*dispwc),Th1)+SJTP((Th1*dispwc).*(Th1*dispwc),RR1))...
    +SJTP(ri2,2*SJTP((R1*dispwc).*(ThTh1*dispwc),R1)+SJTP((R1*dispwc).*(R1*dispwc),ThTh1))...
    +4*SJTP(ri2,SJTP((Th1*dispwc).*(ThR*dispwc),R1)+SJTP((R1*dispwc).*(ThR*dispwc),Th1)...
    +SJTP((R1*dispwc).*(Th1*dispwc),ThR)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（3,4）*(N^2*N^2)矩阵块
JacobiMNL(2*N^2+1:3*N^2,3*N^2+1:4*N^2)=B11*(SJTP(ri1,SJTP(R1*dispwc,R1))+SJTP(R1*dispwc,RR1)...
    +SJTP(RR1*dispwc,R1))...
    +B12*(SJTP(ri1,SJTP(R1*dispwc,R1))+SJTP(ri1,SJTP(RR1*dispwc,II))...
    +SJTP(ri2,SJTP(Th1*dispwc,ThR))+SJTP(ri2,SJTP(ThTh1*dispwc,R1)))...
    +B22*(SJTP(ri3,SJTP(Th1*dispwc,Th1))+SJTP(ri3,SJTP(ThTh1*dispwc,II)))...
    +B44*(-SJTP(ri3,SJTP(Th1*dispwc,Th1))+SJTP(ri2,SJTP(Th1*dispwc,ThR))...
    +SJTP(ri2,SJTP(R1*dispwc,ThTh1))+2*SJTP(ri2,SJTP(ThR*dispwc,Th1)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（3,5）*(N^2*N^2)矩阵块
JacobiMNL(2*N^2+1:3*N^2,4*N^2+1:5*N^2)=B12*(SJTP(ri1,SJTP(R1*dispwc,ThR))...
    +SJTP(RR1*dispwc,Th1))...
    +B22*(SJTP(ri3,SJTP(Th1*dispwc,ThTh1))+SJTP(ri3,SJTP(ThTh1*dispwc,Th1)))...
    +B44*(SJTP(ri1,SJTP(Th1*dispwc,RR1))+SJTP(ri3,SJTP(Th1*dispwc,II))...
    -SJTP(ri2,SJTP(Th1*dispwc,R1))+SJTP(ri1,SJTP(R1*dispwc,ThR))...
    -SJTP(ri2,SJTP(R1*dispwc,Th1))+2*SJTP(ri1,SJTP(ThR*dispwc,R1))...
    -2*SJTP(ri2,SJTP(ThR*dispwc,II)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（4,3）*(N^2*N^2)矩阵块
JacobiMNL(3*N^2+1:4*N^2,2*N^2+1:3*N^2)=B11*(SJTP(RR1*dispwc,R1)+SJTP(R1*dispwc,RR1)...
    +1/2*SJTP(ri1,2*SJTP(R1*dispwc,R1)))...
    +B12*(-1/2*SJTP(ri3,2*SJTP(Th1*dispwc,Th1))...
    +SJTP(ri2,SJTP(ThR*dispwc,Th1)+SJTP(Th1*dispwc,ThR))...
    -1/2*SJTP(ri1,2*SJTP(R1*dispwc,R1)))...
    -B22*(1/2*SJTP(ri3,2*SJTP(Th1*dispwc,Th1)))...
    +B44*(SJTP(ri2,SJTP(ThR*dispwc,Th1)+SJTP(Th1*dispwc,ThR))...
    +SJTP(ri2,SJTP(ThTh1*dispwc,R1)+SJTP(R1*dispwc,ThTh1)));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%赋值（5,3）*(N^2*N^2)矩阵块
JacobiMNL(4*N^2+1:5*N^2,2*N^2+1:3*N^2)=B12*SJTP(ri1,SJTP(ThR*dispwc,R1)...
    +SJTP(R1*dispwc,ThR))...
    +B22*SJTP(ri3,SJTP(ThTh1*dispwc,Th1)+SJTP(Th1*dispwc,ThTh1))...
    +B44*(SJTP(ri2,SJTP(R1*dispwc,Th1)+SJTP(Th1*dispwc,R1))...
    +SJTP(ri1,SJTP(RR1*dispwc,Th1)+SJTP(Th1*dispwc,RR1))...
    +SJTP(ri1,SJTP(ThR*dispwc,R1)+SJTP(R1*dispwc,ThR)));
%计算原方程组的Jacobian矩阵中的非线性相关项
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%将原方程组的Jacobian矩阵中的线性相关项与非线性相关项相加得到Jacobian矩阵
JacobiY=JacobiMLI+JacobiMNL;%将原方程组的Jacobian矩阵中的线性相关项与非线性相关项相加得到Jacobian矩阵
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%将边界条件带入到Jacobi矩阵中
for i=1:N %将Jacobi矩阵中边界条件对应的方程系数归零
    for j=1:5*N^2
        JacobiY(i,j)=0;
        JacobiY((N-1)*N+i,j)=0;
        JacobiY(N^2+i,j)=0;
        JacobiY(N^2+(N-1)*N+i,j)=0;
        JacobiY(2*N^2+i,j)=0;
        JacobiY(2*N^2+(N-1)*N+i,j)=0;
        JacobiY(3*N^2+i,j)=0;
        JacobiY(3*N^2+(N-1)*N+i,j)=0;
        JacobiY(4*N^2+i,j)=0;
        JacobiY(4*N^2+(N-1)*N+i,j)=0;
    end
end
for j=1:N %将Jacobi矩阵中边界条件对应的方程系数采用拉格朗日插值函数插入
    JacobiY(j,j)=1;
    JacobiY((N-1)*N+j,(N-1)*N+j)=1;
    JacobiY(N^2+j,N^2+j)=1;
    JacobiY(N^2+(N-1)*N+j,N^2+(N-1)*N+j)=1;
    JacobiY(2*N^2+j,2*N^2+j)=1;
    JacobiY(2*N^2+(N-1)*N+j,2*N^2+(N-1)*N+j)=1;
%     JacobiY(3*N^2+j,3*N^2+j)=1;
%     JacobiY(3*N^2+(N-1)*N+j,3*N^2+(N-1)*N+j)=1;
    JacobiY(4*N^2+j,4*N^2+j)=1;
    JacobiY(4*N^2+(N-1)*N+j,4*N^2+(N-1)*N+j)=1;
end %将边界条件带入到Jacobi矩阵中
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%求边界条件的Jacobi
JacobiSSBCL=zeros(N^2,5*N^2);
for i=1:N %将边界条件中的方程系数phir不等于零的项插入
    for j=1:N^2
        JacobiSSBCL(i,j)=B11*R1(i,j)+B12*1/r(1,ceil(i/N))*LL(i,j)+B44*1/r(1,ceil(i/N))^2*Th1(i,j);
        JacobiSSBCL(i,N^2+j)=B12*1/r(1,ceil(i/N))*Th1(i,j)+B44*(1/r(1,ceil(i/N))*R1(i,j)-1/r(1,ceil(i/N))^2*LL(i,j));
        JacobiSSBCL(i,3*N^2+j)=D11*R1(i,j)+D12*1/r(1,ceil(i/N))*LL(i,j)+D44*1/r(1,ceil(i/N))^2*Th1(i,j);
        JacobiSSBCL(i,4*N^2+j)=D12*1/r(1,ceil(i/N))*Th1(i,j)+D44*(1/r(1,ceil(i/N))*R1(i,j)-1/r(1,ceil(i/N))^2*LL(i,j));
        JacobiSSBCL((N-1)*N+i,j)=B11*R1((N-1)*N+i,j)+B12*1/r(1,ceil(((N-1)*N+i)/N))*LL((N-1)*N+i,j)+B44*1/r(1,ceil(((N-1)*N+i)/N))^2*Th1((N-1)*N+i,j);
        JacobiSSBCL((N-1)*N+i,N^2+j)=B12*1/r(1,ceil(((N-1)*N+i)/N))*Th1((N-1)*N+i,j)+B44*(1/r(1,ceil(((N-1)*N+i)/N))*R1((N-1)*N+i,j)-1/r(1,ceil(((N-1)*N+i)/N))^2*LL((N-1)*N+i,j));
        JacobiSSBCL((N-1)*N+i,3*N^2+j)=D11*1/r(1,ceil(((N-1)*N+i)/N))*R1((N-1)*N+i,j)+D12*1/r(1,ceil(((N-1)*N+i)/N))*LL((N-1)*N+i,j)+D44*1/r(1,ceil(((N-1)*N+i)/N))^2*Th1((N-1)*N+i,j);
        JacobiSSBCL((N-1)*N+i,4*N^2+j)=D12*1/r(1,ceil(((N-1)*N+i)/N))*Th1((N-1)*N+i,j)+D44*(1/r(1,ceil(((N-1)*N+i)/N))*R1((N-1)*N+i,j)-1/r(1,ceil(((N-1)*N+i)/N))^2*LL((N-1)*N+i,j));
    end
end
JacobiSSBCN=zeros(N^2,5*N^2);
JacobiSSBCN(1:N^2,2*N^2+1:3*N^2)=B11*SJTP(R1*dispwc,R1)+B12*SJTP(ri2,SJTP(Th1*dispwc,Th1))+B44*SJTP(ri2,SJTP(Th1*dispwc,R1)+SJTP(R1*dispwc,Th1));
JacobiSSBC=JacobiSSBCL+JacobiSSBCN;
for i=1:N %将边界条件中非线性项代入Jacobi矩阵中
    for j=1:5*N^2
        JacobiY(3*N^2+i,j)=JacobiSSBC(i,j);
        JacobiY(3*N^2+(N-1)*N+i,j)=JacobiSSBC((N-1)*N+i,j);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%求边界条件的Jacobi
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
rankY=rank(JacobiY);